spring.application.name=distributedjobprocessingplatform
spring.datasource.url=jdbc:postgresql://localhost:5432/distributed_job_platform
spring.datasource.username=postgres
spring.datasource.password=system

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
