spring.application.name=distributedjobprocessingplatform
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/distributed_job_platform
spring.datasource.username=postgres
spring.datasource.password=system
spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
